package restou.greeting;


query "get greeting"()
    greeting : Greeting()
end

rule "greet master"
    when
        person : Person( name == "rettori")
    then
        String salutation = "Hello UHG2 workshop  " + person.getName() + "! BPM64 Hello from biz central to my local openshift env";
        insert(new Greeting(salutation));
end
rule "greet strangers"
    when
        person : Person( name != "rettori")
    then
        String salutation = "hello UHG2 workshop  THANK YOU FOR BEING HERE , BPM64 Hello from biz central to OSE to 3scale " + person.getName();
        insert(new Greeting(salutation));
end
